#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd "${BASEDIR}" >/dev/null

echo "-- Installing submodules"
git submodule update --init --recursive

echo "-- Installing dotbot"
./install-dotbot

if [[ $OSTYPE == darwin* ]]; then
	echo "-- Running OSX install script"
	pushd osx >/dev/null
	./osx-install.sh;
	popd >/dev/null # osx
fi

if ! command -v nvm >/dev/null 2>&1; then
	echo "-- Installing nvm"
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
fi

echo "-- Installing/updating node"
nvm install node

if [ -f "${BASEDIR}/npm-packages" ]; then
	echo "-- Installing/upgrading npm packages"
	INSTALLED_NPM_MODULES=$(npm ls -g --depth=0)
	OUTDATED_NPM_MODULES=$(npm outdated -g --depth=0)
	while read -u 30 p; do
		if ! echo "${INSTALLED_NPM_MODULES}" | grep -q " ${p}@"; then
			npm install -g ${p}
		elif echo "${OUTDATED_NPM_MODULES}" | grep -q "^${p}\s"; then
			npm update -g ${p}
		fi
	done 30<"${BASEDIR}/npm-packages"
fi

popd >/dev/null # "${BASEDIR}"
