#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd "${BASEDIR}" >/dev/null

echo "-- Installing submodules"
git submodule update --init --recursive

echo "-- Installing dotbot"
./install-dotbot

if [[ $OSTYPE == darwin* ]]; then
	echo "-- Running OSX install script"
	pushd osx >/dev/null
	./osx-install.sh;
	popd >/dev/null # osx
fi

popd >/dev/null # "${BASEDIR}"
