#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
if [ -e .git/tags.currentpid && -e .git/tags.`cat .git/tags.currentpid` ]
then
        kill -6 `cat .git/tags.currentpid`
fi
echo $$ > .git/tags.currentpid
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript
mv .git/tags.$$ .git/tags
rm -f .git/tags.currentpid
